### ISSUE TITLE
Generate a recML file given a vcdfile

### ISSUE THREAD

**Issue by wa5wi5ou** [toem/impulse#44]
Hi,

I wander if there is a way to generate a recML file given a vcd file.

Thanx,

Khaled

**Comment by thomasAtToem** [comment]
The only way to generate a recMl/recMz file is to open a vcd with the 
Viewer and save as recMl/recMz .
thanks,
thomas
Am 2017-03-23 10:22, schrieb wa5wi5ou:

**Comment by wa5wi5ou** [comment]
Thanks Thomas, that helps a lot.
I want to know how to do a diff between two signals?

Thanks

**Comment by thomasAtToem** [comment]
Select 2 files -> Context menu -> Impulse -> Compare with Each other.

Am 2017-03-23 11:40, schrieb Klai:
