### ISSUE TITLE
Pie chart with n signals

### ISSUE THREAD

**Issue by wa5wi5ou** [toem/impulse#47]
Hi Tomas,

How can I display 3 signals in a same Pie Chart? for example; I have 3 signals: sig1, sig2 and sig 3, and I want to put them in a pie chart to have a percentage of each one.

Thanks

KLAI

**Comment by thomasAtToem** [comment]
Hi Klai,

* Define a signal script plot with all the inputs.
* Define a script that reads the relevant information from the input
*  and creates a struct signal with the extracted information as members.

Use the existing examples as base.


thanks,
thomas
