### ISSUE TITLE
String variable in fst file

### ISSUE THREAD

**Issue by wa5wi5ou** [toem/impulse#49]
Hi,

How can I display string variable in Impulse of an FST file?
I tried to open an FST file that contains a string variables, but there is no value in the viewer.

Thanx

**Comment by thomasAtToem** [comment]
Hi Klai,

could you attach an example fst file ?

thanks


Am 2017-08-31 15:16, schrieb Klai:

**Comment by wa5wi5ou** [comment]
Hi Thomas,

Please find attached an example of fst file with string variables.

[test_str.zip](https://github.com/toem/impulse/files/1267184/test_str.zip)

**Comment by thomasAtToem** [comment]
I assume something wrong with the fst as i can not open it with gtkwave.
As fst is from gtkwave, it can be used as a reference.
In Impulse i can read the var names, but it seems nothing inside.
Could you please check ?

thanks,
thomas

Am 2017-08-31 15:28, schrieb Klai:

**Comment by wa5wi5ou** [comment]
In deed, I can open it with gtkwave,
Please find attached a capture of my screen.

klai
![capture](https://user-images.githubusercontent.com/5052448/29928572-a5dca65a-8e69-11e7-95bf-a85906593684.PNG)

**Comment by wa5wi5ou** [comment]
And here is a capture of Impulse viewer.
there is nothing inside the variable, but in gtkwave , it display "VALUE" , the string that I affected to the variables and created the fst file.

![capture2](https://user-images.githubusercontent.com/5052448/29929111-edee9074-8e6a-11e7-8dbe-4f0e2eefa005.PNG)

**Comment by thomasAtToem** [comment]
With latest release 1.8.16 strings are working.
