### ISSUE TITLE
'impulse' tab missing in Debug configuration

### ISSUE THREAD

**Issue by darkopetrovic** [toem/impulse#52]
I'm trying to use Impulse in real time with Segger RTT but the 'impulse' tab in the Debug configuration is missing. I followed the post on this [page](http://toem.de/index.php/projects/impulse/articles/98-using-seggers-system-viewer-with-impulse) but I don't have the 'impulse' tab as shown in the video. Is that normal? 

I'm using impulse version 1.8.34 and Eclipse Oxygen (4.7.3a). I tried to connect by opening the port (J-Link Adapter) manually but cannot see any signal. 

Note that everythings works with my applicaiton in the Segger SystemView 2.52a).

Many thanks. 
Darko

**Comment by thomasAtToem** [comment]
Hello Darko,

which launcher are you using ? (You may send a picture of the launcher configuration).
Are you using a special/commercial  eclipse IDE or the standard CDT ?

thanks,
thomas

**Comment by darkopetrovic** [comment]
Hello Thomas,

I'm using the standard CDT and the GDB SEGGER J-Link Debugger (installed with GNU MCU Eclipse 4.3.3 from http://gnu-mcu-eclipse.netlify.com/v4-neon-updates).

![2018-05-16_084709](https://user-images.githubusercontent.com/1554288/40100849-c4a2cde8-58e5-11e8-9483-977d402f8d9b.png)

thanks

**Comment by thomasAtToem** [comment]
Hi Darko,

we will add the launcher tab group configurations for the given 
extensions to our plugin.
Release should be end of this week.

thanks,
thomas


Am 2018-05-15 16:33, schrieb Darko Petrovic:

**Comment by thomasAtToem** [comment]
Release in 1.8.35 - please try !

**Comment by darkopetrovic** [comment]
Thanks, the impulse tab is now visible.
